image: weboaks/node-karma-protractor-chrome

variables:
  VERSION_ID: 0.1.$(date +%Y%m%d%H%M)

stages:
  - test
  - e2e
  - build

test:
  stage: test
  script:
    - yarn
    - yarn ng -- lint
    - yarn test
  only:
    - master

e2e:
  stage: e2e
  script:
    - yarn
    - yarn e2e
  only:
    - master

build:
  image: electronuserland/builder:wine
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/release/*.*
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - yarn && yarn electron:windows
  only:
    - master
