image: weboaks/node-karma-protractor-chrome

variables:
  VERSION_ID: '0.0.$CI_PIPELINE_ID'

stages:
  - build

test:
  stage: test
  script:
    - yarn
    - yarn ng -- lint
    - yarn test
  only:
    - master

e2e:
  stage: e2e
  script:
    - yarn
    - yarn e2e
  only:
    - master

build:
  image: slauta93/electron-builder-win
  stage: build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/release/*.*
  script:
    - sed "s/0.0.0/${VERSION_ID}/g" package.json > _package.json && mv _package.json package.json
    - yarn
    - yarn electron:windows
  only:
    - master
